# Generated by Django 4.2.6 on 2023-11-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(to='courses.tag'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
